# As in M2B from/to properties can be automatically mapped when they have
# the same high-level name.

[[rule]]
# From the Book
from = "Channel"
# Into message
to = "ChannelEdit"
operation = "update"
# The static message parameters
# Can be often empty
# Can be inferred from required message parameters
ids = [
	{ from="Id", to="ChannelId" },
]
# The dynamic message parameters
# from is the property which gets updated, to is the field in the message
properties = [
	# Function which reads a value form the book and splits it up
	# into multiple message parameters
	# fn bla(Channel, MaxClientChannelInherited) -> (type of asd)
	#{ from="MaxClientChannelInherited", function="Bla", tolist=["asd"] },
]

[[rule]]
from = "Client"
to = "ClientEdit"
operation = "update"
ids = [
	{ from="Id", to="ClientId" },
]

# The original properties are on the client object, but we can only change our
# own properties, so these methods are available on the connection.
[[rule]]
from = "Connection"
to = "ClientUpdate"
operation = "update"
properties = [
	{ from="Name", type="str", function="ReturnSome", tolist=["Name"] },
	{ from="InputMuted", type="bool", function="ReturnSome", tolist=["InputMuted"] },
	{ from="OutputMuted", type="bool", function="ReturnSome", tolist=["OutputMuted"] },
	{ from="away", type="str?", function="AwayFunB2m", tolist=["IsAway", "AwayMessage"] },
]

[[rule]]
from = "Connection"
to = "Disconnect"
operation = "remove"

[[rule]]
from = "Client"
to = "ServerGroupAddClient"
operation = "add"
ids = [
	{ from="DatabaseId", to="ClientDbId" },
]
properties = [
	{ from="ServerGroup", to="ServerGroupId" },
]

[[rule]]
from = "Client"
to = "ServerGroupDelClient"
operation = "remove"
ids = [
	{ from="DatabaseId", to="ClientDbId" },
]
properties = [
	{ from="ServerGroups", function="GetId", tolist=["ServerGroupId"] },
]

[[rule]]
from = "Client"
to = "ClientMove"
operation = "update"
ids = [
	{ from="Id", to="ClientId" },
	{ function="GetEmptyString", tolist=["ChannelPassword"] },
]
properties = [
	{ from="Channel", to="ChannelId" },
]

[[rule]]
from = "Client"
to = "ClientMove"
operation = "update"
ids = [
	{ from="Id", to="ClientId" },
	{ from="Password", type="str", function="ReturnSome", tolist=["ChannelPassword"] },
]
properties = [
	{ from="ChannelWithPassword", type="ChannelId", function="Identity", tolist=["ChannelId"] },
]

[[rule]]
from = "ServerGroup"
to = "ServerGroupAddClient"
operation = "add"
ids = [
	{ from="Id", to="ServerGroupId" },
]
properties = [
	{ from="Client", to="ClientDbId" },
]

[[rule]]
from = "ServerGroup"
to = "ServerGroupDelClient"
operation = "remove"
ids = [
	{ from="Id", to="ServerGroupId" },
	# Not an id attribute of the server group, but we want to have it as an
	# argument.
	{ from="Client", to="ClientDbId" },
]
