# All properties which have an identical 'High-Level' name are copied implicitly

[[rule]]
from = "InitServer"
id = []
to = "Server"
operation = "add"
properties = [
	{ from="ServerPlatform", to="Platform" },
	{ from="ServerVersion", to="Version" },
	{ from="ServerCreated", to="Created" },
	{ from="ServerIp", to="Ips" },
	# ClientName, ClientId, TalkPower, NeededServerqueryViewPower
	{ function="SetClientDataFun", tolist=[] },
]

[[rule]]
from = "ChannelCreated"
id = ["ChannelId"]
to = "Channel"
# add/update/remove
operation = "add"
properties = [
	{ from="ParentId", to="Parent" },
	{ function="MaxClientsCcFun", tolist=["MaxClients", "MaxFamilyClients"] },
	{ function="ChannelTypeCcFun", tolist=["ChannelType"] },
	{ function="ReturnFalse", tolist=["ForcedSilence"] },
	{ function="ReturnNone", tolist=["IsPrivate"] },
	{ function="ReturnFalse", tolist=["Subscribed"] },
	{ function="ReturnNone", tolist=["PermissionHints"] },
	{ function="ReturnNone", tolist=["OptionalData"] },
	{ function="ChannelOrderCcFun", tolist=["Order"] },
]

[[rule]]
from = "ChannelDeleted"
id = ["ChannelId"]
to = "Channel"
operation = "remove"

[[rule]]
from = "ChannelEdited"
id = ["ChannelId"]
to = "Channel"
operation = "update"
properties = [
	{ function="MaxClientsCeFun", tolist=["MaxClients", "MaxFamilyClients"] },
	{ function="ChannelTypeCeFun", tolist=["ChannelType"] },
	{ function="ChannelOrderCeFun", tolist=["Order"] },
]

[[rule]]
from = "ChannelList"
id = ["ChannelId"]
to = "Channel"
operation = "add"
properties = [
	{ from="ParentId", to="Parent" },
	{ function="MaxClientsClFun", tolist=["MaxClients", "MaxFamilyClients"] },
	{ function="ChannelTypeClFun", tolist=["ChannelType"] },
	{ function="ReturnFalse", tolist=["Subscribed"] },
	{ function="ReturnNone", tolist=["PermissionHints"] },
	{ function="ReturnNone", tolist=["OptionalData"] },
]

[[rule]]
from = "ChannelMoved"
id = ["ChannelId"]
to = "Channel"
operation = "update"
properties = [
	{ from="ParentId", to="Parent" },
	{ function="ChannelOrderCmFun", tolist=["Order"] },
]

[[rule]]
from = "ChannelSubscribed"
id = ["ChannelId"]
to = "Channel"
operation = "update"
properties = [
	{ function="ChannelSubscribeFun", tolist=["Subscribed"] },
]

[[rule]]
from = "ChannelUnsubscribed"
id = ["ChannelId"]
to = "Channel"
operation = "update"
properties = [
	{ function="ChannelUnsubscribeFun", tolist=["Subscribed"] },
]

[[rule]]
from = "ClientChannelGroupChanged"
id = ["ClientId"]
to = "Client"
operation = "update"

[[rule]]
from = "ClientEnterView"
id = ["ClientId"]
to = "Client"
operation = "add"
properties = [
	{ from="TargetChannelId", to="Channel" },
	{ function="AwayCevFun", tolist=["AwayMessage"] },
	{ function="ClientTypeCevFun", tolist=["ClientType"] },
	{ function="TalkPowerCevFun", tolist=["TalkPowerRequest"] },
	{ function="ReturnNone", tolist=["PermissionHints"] },
	{ function="ReturnNone", tolist=["OptionalData"] },
	{ function="ReturnNone", tolist=["ConnectionData"] },
]

[[rule]]
from = "ClientLeftView"
id = ["ClientId"]
to = "Client"
operation = "remove"

[[rule]]
from = "ClientMoved"
id = ["ClientId"]
to = "Client"
operation = "update"
properties = [
	{ from="TargetChannelId", to="Channel" },
]

[[rule]]
from = "ClientConnectionInfo"
id = ["ClientId"]
to = "ConnectionClientData"
operation = "add"
properties = [
	{ function="AddressFun", tolist=["ClientAddress"] },
]

[[rule]]
from = "ClientServerGroupAdded"
id = ["ClientId"]
to = "Client"
operation = "update"
properties = [
	{ from="ServerGroupId", to="ServerGroups", operation="add" },
	# We explicitely throw away the server group name.
	# Otherwise it would overwrite our client name because of automated
	# matching.
	{ function="VoidFun", tolist=["Name"] },
]

[[rule]]
from = "ClientServerGroupRemoved"
id = ["ClientId"]
to = "Client"
operation = "update"
properties = [
	{ from="ServerGroupId", to="ServerGroups", operation="remove" },
	{ function="VoidFun", tolist=["Name"] },
]

[[rule]]
from = "ClientUpdated"
id = ["ClientId"]
to = "Client"
operation = "update"
properties = [
	{ function="AwayCuFun", tolist=["AwayMessage"] },
	{ function="TalkPowerCuFun", tolist=["TalkPowerRequest"] },
]

[[rule]]
from = "ServerGroupList"
id = ["ServerGroupId"]
to = "ServerGroup"
operation = "add"

[[rule]]
from = "ServerEdited"
id = []
to = "Server"
operation = "update"

[[rule]]
from = "ChannelPermissionHints"
id = ["ChannelId"]
to = "Channel"
operation = "update"
properties = [
	{ from="Flags", to="PermissionHints" },
]

[[rule]]
from = "ClientPermissionHints"
id = ["ClientId"]
to = "Client"
operation = "update"
properties = [
	{ from="Flags", to="PermissionHints" },
]
